spring.application.name=student-management

spring.datasource.url=jdbc:postgresql://localhost:5432/student_management
spring.datasource.username=postgres
spring.datasource.password=secret@123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


